/*! URI.js v1.7.1 http://medialize.github.com/URI.js/ */
/* build contains: IPv6.js, punycode.js, SecondLevelDomains.js, URI.js, URITemplate.js, jquery.URI.js, URI.fragmentQuery.js */
(function(){("undefined"!==typeof module&&module.exports?module.exports:window).IPv6={best:function(d){var d=d.toLowerCase().split(":"),j=d.length,i=8;""===d[0]&&""===d[1]&&""===d[2]?(d.shift(),d.shift()):""===d[0]&&""===d[1]?d.shift():""===d[j-1]&&""===d[j-2]&&d.pop();j=d.length;-1!==d[j-1].indexOf(".")&&(i=7);var k;for(k=0;k<j&&""!==d[k];k++);if(k<i)for(d.splice(k,1,"0000");d.length<i;)d.splice(k,0,"0000");for(k=0;k<i;k++){for(var j=d[k].split(""),e=0;3>e;e++)if("0"===j[0]&&1<j.length)j.splice(0,
1);else break;d[k]=j.join("")}var j=-1,l=e=0,q=-1,g=!1;for(k=0;k<i;k++)g?"0"===d[k]?l+=1:(g=!1,l>e&&(j=q,e=l)):"0"==d[k]&&(g=!0,q=k,l=1);l>e&&(j=q,e=l);1<e&&d.splice(j,e,"");j=d.length;i="";""===d[0]&&(beststr=":");for(k=0;k<j;k++){i+=d[k];if(k===j-1)break;i+=":"}""===d[j-1]&&(i+=":");return i}}})();
(function(d){function j(a){throw RangeError(B[a]);}function i(a,c){for(var f=a.length;f--;)a[f]=c(a[f]);return a}function k(a){for(var c=[],f=0,b=a.length,n,d;f<b;)n=a.charCodeAt(f++),55296==(n&63488)&&(d=a.charCodeAt(f++),(55296!=(n&64512)||56320!=(d&64512))&&j("ucs2decode"),n=((n&1023)<<10)+(d&1023)+65536),c.push(n);return c}function e(a){return i(a,function(a){var c="";55296==(a&63488)&&j("ucs2encode");65535<a&&(a-=65536,c+=y(a>>>10&1023|55296),a=56320|a&1023);return c+=y(a)}).join("")}function l(f,
b,n){for(var d=0,f=n?u(f/c):f>>1,f=f+u(f/b);f>v*t>>1;d+=s)f=u(f/v);return u(d+(v+1)*f/(f+a))}function q(a){var c=[],b=a.length,d,h=0,g=n,m=f,r,i,k,p,q;r=a.lastIndexOf(A);0>r&&(r=0);for(i=0;i<r;++i)128<=a.charCodeAt(i)&&j("not-basic"),c.push(a.charCodeAt(i));for(r=0<r?r+1:0;r<b;){i=h;d=1;for(k=s;;k+=s){r>=b&&j("invalid-input");p=a.charCodeAt(r++);p=10>p-48?p-22:26>p-65?p-65:26>p-97?p-97:s;(p>=s||p>u((w-h)/d))&&j("overflow");h+=p*d;q=k<=m?o:k>=m+t?t:k-m;if(p<q)break;p=s-q;d>u(w/p)&&j("overflow");d*=
p}d=c.length+1;m=l(h-i,d,0==i);u(h/d)>w-g&&j("overflow");g+=u(h/d);h%=d;c.splice(h++,0,g)}return e(c)}function g(a){var c,b,d,h,e,g,m,r,i,p=[],q,x,v,a=k(a);q=a.length;c=n;b=0;e=f;for(g=0;g<q;++g)i=a[g],128>i&&p.push(y(i));for((d=h=p.length)&&p.push(A);d<q;){m=w;for(g=0;g<q;++g)i=a[g],i>=c&&i<m&&(m=i);x=d+1;m-c>u((w-b)/x)&&j("overflow");b+=(m-c)*x;c=m;for(g=0;g<q;++g)if(i=a[g],i<c&&++b>w&&j("overflow"),i==c){r=b;for(m=s;;m+=s){i=m<=e?o:m>=e+t?t:m-e;if(r<i)break;v=r-i;r=s-i;p.push(y(i+v%r+22+75*(26>
i+v%r)-0));r=u(v/r)}p.push(y(r+22+75*(26>r)-0));e=l(b,x,d==h);b=0;++d}++b;++c}return p.join("")}var b,h="function"==typeof define&&"object"==typeof define.amd&&define.amd&&define,m="object"==typeof exports&&exports,p="object"==typeof module&&module,w=2147483647,s=36,o=1,t=26,a=38,c=700,f=72,n=128,A="-",r=/[^ -~]/,x=/^xn--/,B={overflow:"Overflow: input needs wider integers to process.",ucs2decode:"UCS-2(decode): illegal sequence",ucs2encode:"UCS-2(encode): illegal value","not-basic":"Illegal input >= 0x80 (not a basic code point)",
"invalid-input":"Invalid input"},v=s-o,u=Math.floor,y=String.fromCharCode,z;b={version:"0.3.0",ucs2:{decode:k,encode:e},decode:q,encode:g,toASCII:function(a){return i(a.split("."),function(a){return r.test(a)?"xn--"+g(a):a}).join(".")},toUnicode:function(a){return i(a.split("."),function(a){return x.test(a)?q(a.slice(4).toLowerCase()):a}).join(".")}};if(m)if(p&&p.exports==m)p.exports=b;else for(z in b)b.hasOwnProperty(z)&&(m[z]=b[z]);else h?define("punycode",b):d.punycode=b})(this);
(function(){var d={list:{ac:"com|gov|mil|net|org",ae:"ac|co|gov|mil|name|net|org|pro|sch",af:"com|edu|gov|net|org",al:"com|edu|gov|mil|net|org",ao:"co|ed|gv|it|og|pb",ar:"com|edu|gob|gov|int|mil|net|org|tur",at:"ac|co|gv|or",au:"asn|com|csiro|edu|gov|id|net|org",ba:"co|com|edu|gov|mil|net|org|rs|unbi|unmo|unsa|untz|unze",bb:"biz|co|com|edu|gov|info|net|org|store|tv",bh:"biz|cc|com|edu|gov|info|net|org",bn:"com|edu|gov|net|org",bo:"com|edu|gob|gov|int|mil|net|org|tv",br:"adm|adv|agr|am|arq|art|ato|b|bio|blog|bmd|cim|cng|cnt|com|coop|ecn|edu|eng|esp|etc|eti|far|flog|fm|fnd|fot|fst|g12|ggf|gov|imb|ind|inf|jor|jus|lel|mat|med|mil|mus|net|nom|not|ntr|odo|org|ppg|pro|psc|psi|qsl|rec|slg|srv|tmp|trd|tur|tv|vet|vlog|wiki|zlg",
bs:"com|edu|gov|net|org",bz:"du|et|om|ov|rg",ca:"ab|bc|mb|nb|nf|nl|ns|nt|nu|on|pe|qc|sk|yk",ck:"biz|co|edu|gen|gov|info|net|org",cn:"ac|ah|bj|com|cq|edu|fj|gd|gov|gs|gx|gz|ha|hb|he|hi|hl|hn|jl|js|jx|ln|mil|net|nm|nx|org|qh|sc|sd|sh|sn|sx|tj|tw|xj|xz|yn|zj",co:"com|edu|gov|mil|net|nom|org",cr:"ac|c|co|ed|fi|go|or|sa",cy:"ac|biz|com|ekloges|gov|ltd|name|net|org|parliament|press|pro|tm","do":"art|com|edu|gob|gov|mil|net|org|sld|web",dz:"art|asso|com|edu|gov|net|org|pol",ec:"com|edu|fin|gov|info|med|mil|net|org|pro",
eg:"com|edu|eun|gov|mil|name|net|org|sci",er:"com|edu|gov|ind|mil|net|org|rochest|w",es:"com|edu|gob|nom|org",et:"biz|com|edu|gov|info|name|net|org",fj:"ac|biz|com|info|mil|name|net|org|pro",fk:"ac|co|gov|net|nom|org",fr:"asso|com|f|gouv|nom|prd|presse|tm",gg:"co|net|org",gh:"com|edu|gov|mil|org",gn:"ac|com|gov|net|org",gr:"com|edu|gov|mil|net|org",gt:"com|edu|gob|ind|mil|net|org",gu:"com|edu|gov|net|org",hk:"com|edu|gov|idv|net|org",id:"ac|co|go|mil|net|or|sch|web",il:"ac|co|gov|idf|k12|muni|net|org",
"in":"ac|co|edu|ernet|firm|gen|gov|i|ind|mil|net|nic|org|res",iq:"com|edu|gov|i|mil|net|org",ir:"ac|co|dnssec|gov|i|id|net|org|sch",it:"edu|gov",je:"co|net|org",jo:"com|edu|gov|mil|name|net|org|sch",jp:"ac|ad|co|ed|go|gr|lg|ne|or",ke:"ac|co|go|info|me|mobi|ne|or|sc",kh:"com|edu|gov|mil|net|org|per",ki:"biz|com|de|edu|gov|info|mob|net|org|tel",km:"asso|com|coop|edu|gouv|k|medecin|mil|nom|notaires|pharmaciens|presse|tm|veterinaire",kn:"edu|gov|net|org",kr:"ac|busan|chungbuk|chungnam|co|daegu|daejeon|es|gangwon|go|gwangju|gyeongbuk|gyeonggi|gyeongnam|hs|incheon|jeju|jeonbuk|jeonnam|k|kg|mil|ms|ne|or|pe|re|sc|seoul|ulsan",
kw:"com|edu|gov|net|org",ky:"com|edu|gov|net|org",kz:"com|edu|gov|mil|net|org",lb:"com|edu|gov|net|org",lk:"assn|com|edu|gov|grp|hotel|int|ltd|net|ngo|org|sch|soc|web",lr:"com|edu|gov|net|org",lv:"asn|com|conf|edu|gov|id|mil|net|org",ly:"com|edu|gov|id|med|net|org|plc|sch",ma:"ac|co|gov|m|net|org|press",mc:"asso|tm",me:"ac|co|edu|gov|its|net|org|priv",mg:"com|edu|gov|mil|nom|org|prd|tm",mk:"com|edu|gov|inf|name|net|org|pro",ml:"com|edu|gov|net|org|presse",mn:"edu|gov|org",mo:"com|edu|gov|net|org",
mt:"com|edu|gov|net|org",mv:"aero|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro",mw:"ac|co|com|coop|edu|gov|int|museum|net|org",mx:"com|edu|gob|net|org",my:"com|edu|gov|mil|name|net|org|sch",nf:"arts|com|firm|info|net|other|per|rec|store|web",ng:"biz|com|edu|gov|mil|mobi|name|net|org|sch",ni:"ac|co|com|edu|gob|mil|net|nom|org",np:"com|edu|gov|mil|net|org",nr:"biz|com|edu|gov|info|net|org",om:"ac|biz|co|com|edu|gov|med|mil|museum|net|org|pro|sch",pe:"com|edu|gob|mil|net|nom|org|sld",ph:"com|edu|gov|i|mil|net|ngo|org",
pk:"biz|com|edu|fam|gob|gok|gon|gop|gos|gov|net|org|web",pl:"art|bialystok|biz|com|edu|gda|gdansk|gorzow|gov|info|katowice|krakow|lodz|lublin|mil|net|ngo|olsztyn|org|poznan|pwr|radom|slupsk|szczecin|torun|warszawa|waw|wroc|wroclaw|zgora",pr:"ac|biz|com|edu|est|gov|info|isla|name|net|org|pro|prof",ps:"com|edu|gov|net|org|plo|sec",pw:"belau|co|ed|go|ne|or",ro:"arts|com|firm|info|nom|nt|org|rec|store|tm|www",rs:"ac|co|edu|gov|in|org",sb:"com|edu|gov|net|org",sc:"com|edu|gov|net|org",sh:"co|com|edu|gov|net|nom|org",
sl:"com|edu|gov|net|org",st:"co|com|consulado|edu|embaixada|gov|mil|net|org|principe|saotome|store",sv:"com|edu|gob|org|red",sz:"ac|co|org",tr:"av|bbs|bel|biz|com|dr|edu|gen|gov|info|k12|name|net|org|pol|tel|tsk|tv|web",tt:"aero|biz|cat|co|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel",tw:"club|com|ebiz|edu|game|gov|idv|mil|net|org",mu:"ac|co|com|gov|net|or|org",mz:"ac|co|edu|gov|org",na:"co|com",nz:"ac|co|cri|geek|gen|govt|health|iwi|maori|mil|net|org|parliament|school",
pa:"abo|ac|com|edu|gob|ing|med|net|nom|org|sld",pt:"com|edu|gov|int|net|nome|org|publ",py:"com|edu|gov|mil|net|org",qa:"com|edu|gov|mil|net|org",re:"asso|com|nom",ru:"ac|adygeya|altai|amur|arkhangelsk|astrakhan|bashkiria|belgorod|bir|bryansk|buryatia|cbg|chel|chelyabinsk|chita|chukotka|chuvashia|com|dagestan|e-burg|edu|gov|grozny|int|irkutsk|ivanovo|izhevsk|jar|joshkar-ola|kalmykia|kaluga|kamchatka|karelia|kazan|kchr|kemerovo|khabarovsk|khakassia|khv|kirov|koenig|komi|kostroma|kranoyarsk|kuban|kurgan|kursk|lipetsk|magadan|mari|mari-el|marine|mil|mordovia|mosreg|msk|murmansk|nalchik|net|nnov|nov|novosibirsk|nsk|omsk|orenburg|org|oryol|penza|perm|pp|pskov|ptz|rnd|ryazan|sakhalin|samara|saratov|simbirsk|smolensk|spb|stavropol|stv|surgut|tambov|tatarstan|tom|tomsk|tsaritsyn|tsk|tula|tuva|tver|tyumen|udm|udmurtia|ulan-ude|vladikavkaz|vladimir|vladivostok|volgograd|vologda|voronezh|vrn|vyatka|yakutia|yamal|yekaterinburg|yuzhno-sakhalinsk",
rw:"ac|co|com|edu|gouv|gov|int|mil|net",sa:"com|edu|gov|med|net|org|pub|sch",sd:"com|edu|gov|info|med|net|org|tv",se:"a|ac|b|bd|c|d|e|f|g|h|i|k|l|m|n|o|org|p|parti|pp|press|r|s|t|tm|u|w|x|y|z",sg:"com|edu|gov|idn|net|org|per",sn:"art|com|edu|gouv|org|perso|univ",sy:"com|edu|gov|mil|net|news|org",th:"ac|co|go|in|mi|net|or",tj:"ac|biz|co|com|edu|go|gov|info|int|mil|name|net|nic|org|test|web",tn:"agrinet|com|defense|edunet|ens|fin|gov|ind|info|intl|mincom|nat|net|org|perso|rnrt|rns|rnu|tourism",tz:"ac|co|go|ne|or",
ua:"biz|cherkassy|chernigov|chernovtsy|ck|cn|co|com|crimea|cv|dn|dnepropetrovsk|donetsk|dp|edu|gov|if|in|ivano-frankivsk|kh|kharkov|kherson|khmelnitskiy|kiev|kirovograd|km|kr|ks|kv|lg|lugansk|lutsk|lviv|me|mk|net|nikolaev|od|odessa|org|pl|poltava|pp|rovno|rv|sebastopol|sumy|te|ternopil|uzhgorod|vinnica|vn|zaporizhzhe|zhitomir|zp|zt",ug:"ac|co|go|ne|or|org|sc",uk:"ac|bl|british-library|co|cym|gov|govt|icnet|jet|lea|ltd|me|mil|mod|national-library-scotland|nel|net|nhs|nic|nls|org|orgn|parliament|plc|police|sch|scot|soc",
us:"dni|fed|isa|kids|nsn",uy:"com|edu|gub|mil|net|org",ve:"co|com|edu|gob|info|mil|net|org|web",vi:"co|com|k12|net|org",vn:"ac|biz|com|edu|gov|health|info|int|name|net|org|pro",ye:"co|com|gov|ltd|me|net|org|plc",yu:"ac|co|edu|gov|org",za:"ac|agric|alt|bourse|city|co|cybernet|db|edu|gov|grondar|iaccess|imt|inca|landesign|law|mil|net|ngo|nis|nom|olivetti|org|pix|school|tm|web",zm:"ac|co|com|edu|gov|net|org|sch"},has_expression:null,is_expression:null,has:function(j){return!!j.match(d.has_expression)},
is:function(j){return!!j.match(d.is_expression)},get:function(j){return(j=j.match(d.has_expression))&&j[1]||null},init:function(){var j="",i;for(i in d.list)Object.prototype.hasOwnProperty.call(d.list,i)&&(j+="|("+("("+d.list[i]+")."+i)+")");d.has_expression=RegExp(".("+j.substr(1)+")$","i");d.is_expression=RegExp("^("+j.substr(1)+")$","i")}};d.init();"undefined"!==typeof module&&module.exports?module.exports=d:window.SecondLevelDomains=d})();
(function(d){function j(a){return a.replace(/([.*+?^=!:${}()|[\]\/\\])/g,"\\$1")}function i(a){return"[object Array]"===String(Object.prototype.toString.call(a))}function k(a){return encodeURIComponent(a).replace(/[!'()*]/g,escape)}var e="undefined"!==typeof module&&module.exports,l=e?require("./punycode"):window.punycode,q=e?require("./IPv6"):window.IPv6,g=e?require("./SecondLevelDomains"):window.SecondLevelDomains,b=function(a,c){if(!(this instanceof b))return new b(a,c);a===d&&(a=location.href+
"");this.href(a);return c!==d?this.absoluteTo(c):this},e=b.prototype;b.idn_expression=/[^a-z0-9\.-]/i;b.punycode_expression=/(xn--)/i;b.ip4_expression=/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/;b.ip6_expression=/^\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?\s*$/;
b.find_uri_expression=/\b((?:[a-z][\w-]+:(?:\/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}\/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))/ig;b.defaultPorts={http:"80",https:"443",ftp:"21"};b.invalid_hostname_characters=/[^a-zA-Z0-9\.-]/;b.encode=k;b.decode=decodeURIComponent;b.iso8859=function(){b.encode=escape;b.decode=unescape};b.unicode=function(){b.encode=k;b.decode=decodeURIComponent};
b.characters={pathname:{encode:{expression:/%(24|26|2B|2C|3B|3D|3A|40)/ig,map:{"%24":"$","%26":"&","%2B":"+","%2C":",","%3B":";","%3D":"=","%3A":":","%40":"@"}},decode:{expression:/[\/\?#]/g,map:{"/":"%2F","?":"%3F","#":"%23"}}},reserved:{encode:{expression:/%(21|23|24|26|27|28|29|2A|2B|2C|2F|3A|3B|3D|3F|40|5B|5D)/ig,map:{"%3A":":","%2F":"/","%3F":"?","%23":"#","%5B":"[","%5D":"]","%40":"@","%21":"!","%24":"$","%26":"&","%27":"'","%28":"(","%29":")","%2A":"*","%2B":"+","%2C":",","%3B":";","%3D":"="}}}};
b.encodeQuery=function(a){return b.encode(a+"").replace(/%20/g,"+")};b.decodeQuery=function(a){return b.decode((a+"").replace(/\+/g,"%20"))};b.recodePath=function(a){for(var a=(a+"").split("/"),c=0,f=a.length;c<f;c++)a[c]=b.encodePathSegment(b.decode(a[c]));return a.join("/")};b.decodePath=function(a){for(var a=(a+"").split("/"),c=0,f=a.length;c<f;c++)a[c]=b.decodePathSegment(a[c]);return a.join("/")};var h={encode:"encode",decode:"decode"},m,p=function(a,c){return function(f){return b[c](f+"").replace(b.characters[a][c].expression,
function(f){return b.characters[a][c].map[f]})}};for(m in h)b[m+"PathSegment"]=p("pathname",h[m]);b.encodeReserved=p("reserved","encode");b.parse=function(a){var c,f={};c=a.indexOf("#");-1<c&&(f.fragment=a.substring(c+1)||null,a=a.substring(0,c));c=a.indexOf("?");-1<c&&(f.query=a.substring(c+1)||null,a=a.substring(0,c));"//"===a.substring(0,2)?(f.protocol="",a=a.substring(2),a=b.parseAuthority(a,f)):(c=a.indexOf(":"),-1<c&&(f.protocol=a.substring(0,c),"//"===a.substring(c+1,c+3)?(a=a.substring(c+
3),a=b.parseAuthority(a,f)):(a=a.substring(c+1),f.urn=!0)));f.path=a;return f};b.parseHost=function(a,c){var f=a.indexOf("/"),b;-1===f&&(f=a.length);"["===a[0]?(b=a.indexOf("]"),c.hostname=a.substring(1,b)||null,c.port=a.substring(b+2,f)||null):a.indexOf(":")!==a.lastIndexOf(":")?(c.hostname=a.substring(0,f)||null,c.port=null):(b=a.substring(0,f).split(":"),c.hostname=b[0]||null,c.port=b[1]||null);c.hostname&&"/"!==a.substring(f)[0]&&(f++,a="/"+a);return a.substring(f)||"/"};b.parseAuthority=function(a,
c){a=b.parseUserinfo(a,c);return b.parseHost(a,c)};b.parseUserinfo=function(a,c){var f=a.indexOf("@"),d=a.indexOf("/");-1<f&&(-1===d||f<d)?(d=a.substring(0,f).split(":"),c.username=d[0]?b.decode(d[0]):null,c.password=d[1]?b.decode(d[1]):null,a=a.substring(f+1)):(c.username=null,c.password=null);return a};b.parseQuery=function(a){if(!a)return{};a=a.replace(/&+/g,"&").replace(/^\?*&*|&+$/g,"");if(!a)return{};for(var c={},a=a.split("&"),f=a.length,d=0;d<f;d++){var h=a[d].split("="),g=b.decodeQuery(h.shift()),
h=h.length?b.decodeQuery(h.join("=")):null;c[g]?("string"===typeof c[g]&&(c[g]=[c[g]]),c[g].push(h)):c[g]=h}return c};b.build=function(a){var c="";a.protocol&&(c+=a.protocol+":");if(!a.urn&&(c||a.hostname))c+="//";c+=b.buildAuthority(a)||"";"string"===typeof a.path&&("/"!==a.path[0]&&"string"===typeof a.hostname&&(c+="/"),c+=a.path);"string"===typeof a.query&&(c+="?"+a.query);"string"===typeof a.fragment&&(c+="#"+a.fragment);return c};b.buildHost=function(a){var c="";if(a.hostname)b.ip6_expression.test(a.hostname)?
c=a.port?c+("["+a.hostname+"]:"+a.port):c+a.hostname:(c+=a.hostname,a.port&&(c+=":"+a.port));else return"";return c};b.buildAuthority=function(a){return b.buildUserinfo(a)+b.buildHost(a)};b.buildUserinfo=function(a){var c="";a.username&&(c+=b.encode(a.username),a.password&&(c+=":"+b.encode(a.password)),c+="@");return c};b.buildQuery=function(a,c){var f="",n;for(n in a)if(Object.hasOwnProperty.call(a,n)&&n)if(i(a[n]))for(var h={},g=0,e=a[n].length;g<e;g++)a[n][g]!==d&&h[a[n][g]+""]===d&&(f+="&"+b.buildQueryParameter(n,
a[n][g]),!0!==c&&(h[a[n][g]+""]=!0));else a[n]!==d&&(f+="&"+b.buildQueryParameter(n,a[n]));return f.substring(1)};b.buildQueryParameter=function(a,c){return b.encodeQuery(a)+(null!==c?"="+b.encodeQuery(c):"")};b.addQuery=function(a,c,f){if("object"===typeof c)for(var n in c)Object.prototype.hasOwnProperty.call(c,n)&&b.addQuery(a,n,c[n]);else if("string"===typeof c)a[c]===d?a[c]=f:("string"===typeof a[c]&&(a[c]=[a[c]]),i(f)||(f=[f]),a[c]=a[c].concat(f));else throw new TypeError("URI.addQuery() accepts an object, string as the name parameter");
};b.removeQuery=function(a,c,f){if(i(c))for(var f=0,n=c.length;f<n;f++)a[c[f]]=d;else if("object"===typeof c)for(n in c)Object.prototype.hasOwnProperty.call(c,n)&&b.removeQuery(a,n,c[n]);else if("string"===typeof c)if(f!==d)if(a[c]===f)a[c]=d;else{if(i(a[c])){var n=a[c],h={},g,e;if(i(f)){g=0;for(e=f.length;g<e;g++)h[f[g]]=!0}else h[f]=!0;g=0;for(e=n.length;g<e;g++)h[n[g]]!==d&&(n.splice(g,1),e--,g--);a[c]=n}}else a[c]=d;else throw new TypeError("URI.addQuery() accepts an object, string as the first parameter");
};b.commonPath=function(a,c){var f=Math.min(a.length,c.length),b;for(b=0;b<f;b++)if(a[b]!==c[b]){b--;break}if(1>b)return a[0]===c[0]&&"/"===a[0]?"/":"";"/"!==a[b]&&(b=a.substring(0,b).lastIndexOf("/"));return a.substring(0,b+1)};b.withinString=function(a,c){return a.replace(b.find_uri_expression,c)};b.ensureValidHostname=function(a){if(a.match(b.invalid_hostname_characters)){if(!l)throw new TypeError("Hostname '"+a+"' contains characters other than [A-Z0-9.-] and Punycode.js is not available");if(l.toASCII(a).match(b.invalid_hostname_characters))throw new TypeError("Hostname '"+
a+"' contains characters other than [A-Z0-9.-]");}};e.build=function(a){if(!0===a)this._deferred_build=!0;else if(a===d||this._deferred_build)this._string=b.build(this._parts),this._deferred_build=!1;return this};e.clone=function(){return new b(this)};e.toString=function(){return this.build(!1)._string};e.valueOf=function(){return this.toString()};h={protocol:"protocol",username:"username",password:"password",hostname:"hostname",port:"port"};p=function(a){return function(c,b){if(c===d)return this._parts[a]||
"";this._parts[a]=c;this.build(!b);return this}};for(m in h)e[m]=p(h[m]);h={query:"?",fragment:"#"};p=function(a,c){return function(b,g){if(b===d)return this._parts[a]||"";null!==b&&(b+="",b[0]===c&&(b=b.substring(1)));this._parts[a]=b;this.build(!g);return this}};for(m in h)e[m]=p(m,h[m]);h={search:["?","query"],hash:["#","fragment"]};p=function(a,c){return function(b,d){var g=this[a](b,d);return"string"===typeof g&&g.length?c+g:g}};for(m in h)e[m]=p(h[m][1],h[m][0]);e.pathname=function(a,c){if(a===
d||!0===a){var f=this._parts.path||(this._parts.urn?"":"/");return a?b.decodePath(f):f}this._parts.path=a?b.recodePath(a):"/";this.build(!c);return this};e.path=e.pathname;e.href=function(a,c){if(a===d)return this.toString();this._string="";this._parts={protocol:null,username:null,password:null,hostname:null,urn:null,port:null,path:null,query:null,fragment:null};var f=a instanceof b,g="object"===typeof a&&(a.hostname||a.path),h;if("string"===typeof a)this._parts=b.parse(a);else if(f||g)for(h in f=
f?a._parts:a,f)Object.hasOwnProperty.call(this._parts,h)&&(this._parts[h]=f[h]);else throw new TypeError("invalid input");this.build(!c);return this};e.is=function(a){var c=!1,f=!1,d=!1,h=!1,e=!1,m=!1,i=!1,p=!this._parts.urn;this._parts.hostname&&(p=!1,f=b.ip4_expression.test(this._parts.hostname),d=b.ip6_expression.test(this._parts.hostname),c=f||d,e=(h=!c)&&g&&g.has(this._parts.hostname),m=h&&b.idn_expression.test(this._parts.hostname),i=h&&b.punycode_expression.test(this._parts.hostname));switch(a.toLowerCase()){case "relative":return p;
case "absolute":return!p;case "domain":case "name":return h;case "sld":return e;case "ip":return c;case "ip4":case "ipv4":case "inet4":return f;case "ip6":case "ipv6":case "inet6":return d;case "idn":return m;case "url":return!this._parts.urn;case "urn":return!!this._parts.urn;case "punycode":return i}return null};var w=e.protocol,s=e.port,o=e.hostname;e.protocol=function(a,c){if(a!==d&&a&&(a=a.replace(/:(\/\/)?$/,""),a.match(/[^a-zA-z0-9\.+-]/)))throw new TypeError("Protocol '"+a+"' contains characters other than [A-Z0-9.+-]");
return w.call(this,a,c)};e.scheme=e.protocol;e.port=function(a,c){if(this._parts.urn)return a===d?"":this;if(a!==d&&(0===a&&(a=null),a&&(a+="",":"===a[0]&&(a=a.substring(1)),a.match(/[^0-9]/))))throw new TypeError("Port '"+a+"' contains characters other than [0-9]");return s.call(this,a,c)};e.hostname=function(a,c){if(this._parts.urn)return a===d?"":this;if(a!==d){var f={};b.parseHost(a,f);a=f.hostname}return o.call(this,a,c)};e.host=function(a,c){if(this._parts.urn)return a===d?"":this;if(a===d)return this._parts.hostname?
b.buildHost(this._parts):"";b.parseHost(a,this._parts);this.build(!c);return this};e.authority=function(a,c){if(this._parts.urn)return a===d?"":this;if(a===d)return this._parts.hostname?b.buildAuthority(this._parts):"";b.parseAuthority(a,this._parts);this.build(!c);return this};e.userinfo=function(a,c){if(this._parts.urn)return a===d?"":this;if(a===d){if(!this._parts.username)return"";var f=b.buildUserinfo(this._parts);return f.substring(0,f.length-1)}"@"!==a[a.length-1]&&(a+="@");b.parseUserinfo(a,
this._parts);this.build(!c);return this};e.subdomain=function(a,c){if(this._parts.urn)return a===d?"":this;if(a===d){if(!this._parts.hostname||this.is("IP"))return"";var f=this._parts.hostname.length-this.domain().length-1;return this._parts.hostname.substring(0,f)||""}f=this._parts.hostname.length-this.domain().length;f=this._parts.hostname.substring(0,f);f=RegExp("^"+j(f));a&&"."!==a[a.length-1]&&(a+=".");a&&b.ensureValidHostname(a);this._parts.hostname=this._parts.hostname.replace(f,a);this.build(!c);
return this};e.domain=function(a,c){if(this._parts.urn)return a===d?"":this;"boolean"===typeof a&&(c=a,a=d);if(a===d){if(!this._parts.hostname||this.is("IP"))return"";var f=this._parts.hostname.match(/\./g);if(f&&2>f.length)return this._parts.hostname;f=this._parts.hostname.length-this.tld(c).length-1;f=this._parts.hostname.lastIndexOf(".",f-1)+1;return this._parts.hostname.substring(f)||""}if(!a)throw new TypeError("cannot set domain empty");b.ensureValidHostname(a);!this._parts.hostname||this.is("IP")?
this._parts.hostname=a:(f=RegExp(j(this.domain())+"$"),this._parts.hostname=this._parts.hostname.replace(f,a));this.build(!c);return this};e.tld=function(a,c){if(this._parts.urn)return a===d?"":this;"boolean"===typeof a&&(c=a,a=d);if(a===d){if(!this._parts.hostname||this.is("IP"))return"";var b=this._parts.hostname.lastIndexOf("."),b=this._parts.hostname.substring(b+1);return!0!==c&&g&&g.list[b.toLowerCase()]?g.get(this._parts.hostname)||b:b}if(a)if(a.match(/[^a-zA-Z0-9-]/))if(g&&g.is(a))b=RegExp(j(this.tld())+
"$"),this._parts.hostname=this._parts.hostname.replace(b,a);else throw new TypeError("TLD '"+a+"' contains characters other than [A-Z0-9]");else{if(!this._parts.hostname||this.is("IP"))throw new ReferenceError("cannot set TLD on non-domain host");b=RegExp(j(this.tld())+"$");this._parts.hostname=this._parts.hostname.replace(b,a)}else throw new TypeError("cannot set TLD empty");this.build(!c);return this};e.directory=function(a,c){if(this._parts.urn)return a===d?"":this;if(a===d||!0===a){if(!this._parts.path&&
!this._parts.hostname)return"";if("/"===this._parts.path)return"/";var f=this._parts.path.length-this.filename().length-1,f=this._parts.path.substring(0,f)||(this._parts.hostname?"/":"");return a?b.decodePath(f):f}f=this._parts.path.length-this.filename().length;f=this._parts.path.substring(0,f);f=RegExp("^"+j(f));this.is("relative")||(a||(a="/"),"/"!==a[0]&&(a="/"+a));a&&"/"!==a[a.length-1]&&(a+="/");a=b.recodePath(a);this._parts.path=this._parts.path.replace(f,a);this.build(!c);return this};e.filename=
function(a,c){if(this._parts.urn)return a===d?"":this;if(a===d||!0===a){if(!this._parts.path||"/"===this._parts.path)return"";var f=this._parts.path.lastIndexOf("/"),f=this._parts.path.substring(f+1);return a?b.decodePathSegment(f):f}f=!1;"/"===a[0]&&(a=a.substring(1));a.match(/\.?\//)&&(f=!0);var g=RegExp(j(this.filename())+"$"),a=b.recodePath(a);this._parts.path=this._parts.path.replace(g,a);f?this.normalizePath(c):this.build(!c);return this};e.suffix=function(a,c){if(this._parts.urn)return a===
d?"":this;if(a===d||!0===a){if(!this._parts.path||"/"===this._parts.path)return"";var f=this.filename(),g=f.lastIndexOf(".");if(-1===g)return"";f=f.substring(g+1);f=/^[a-z0-9%]+$/i.test(f)?f:"";return a?b.decodePathSegment(f):f}"."===a[0]&&(a=a.substring(1));if(f=this.suffix())g=a?RegExp(j(f)+"$"):RegExp(j("."+f)+"$");else{if(!a)return this;this._parts.path+="."+b.recodePath(a)}g&&(a=b.recodePath(a),this._parts.path=this._parts.path.replace(g,a));this.build(!c);return this};e.segment=function(a,c,
b){var g=this._parts.urn?":":"/",h=this.path(),e="/"===h.substring(0,1),h=h.split(g);"number"!==typeof a&&(b=c,c=a,a=d);if(a!==d&&"number"!==typeof a)throw Error("Bad segment '"+a+"', must be 0-based integer");e&&h.shift();0>a&&(a=Math.max(h.length+a,0));if(c===d)return a===d?h:h[a];if(null===a||h[a]===d)if(i(c))h=c;else{if(c||"string"===typeof c&&c.length)""===h[h.length-1]?h[h.length-1]=c:h.push(c)}else c||"string"===typeof c&&c.length?h[a]=c:h.splice(a,1);e&&h.unshift("");return this.path(h.join(g),
b)};var t=e.query;e.query=function(a,c){return!0===a?b.parseQuery(this._parts.query):a!==d&&"string"!==typeof a?(this._parts.query=b.buildQuery(a),this.build(!c),this):t.call(this,a,c)};e.addQuery=function(a,c,f){var d=b.parseQuery(this._parts.query);b.addQuery(d,a,c);this._parts.query=b.buildQuery(d);"string"!==typeof a&&(f=c);this.build(!f);return this};e.removeQuery=function(a,c,f){var d=b.parseQuery(this._parts.query);b.removeQuery(d,a,c);this._parts.query=b.buildQuery(d);"string"!==typeof a&&
(f=c);this.build(!f);return this};e.addSearch=e.addQuery;e.removeSearch=e.removeQuery;e.normalize=function(){return this._parts.urn?this.normalizeProtocol(!1).normalizeQuery(!1).normalizeFragment(!1).build():this.normalizeProtocol(!1).normalizeHostname(!1).normalizePort(!1).normalizePath(!1).normalizeQuery(!1).normalizeFragment(!1).build()};e.normalizeProtocol=function(a){"string"===typeof this._parts.protocol&&(this._parts.protocol=this._parts.protocol.toLowerCase(),this.build(!a));return this};
e.normalizeHostname=function(a){this._parts.hostname&&(this.is("IDN")&&l?this._parts.hostname=l.toASCII(this._parts.hostname):this.is("IPv6")&&q&&(this._parts.hostname=q.best(this._parts.hostname)),this._parts.hostname=this._parts.hostname.toLowerCase(),this.build(!a));return this};e.normalizePort=function(a){"string"===typeof this._parts.protocol&&this._parts.port===b.defaultPorts[this._parts.protocol]&&(this._parts.port=null,this.build(!a));return this};e.normalizePath=function(a){if(this._parts.urn||
!this._parts.path||"/"===this._parts.path)return this;var c,f,d=this._parts.path,h,g;"/"!==d[0]&&("."===d[0]&&(f=d.substring(0,d.indexOf("/"))),c=!0,d="/"+d);for(d=d.replace(/(\/(\.\/)+)|\/{2,}/g,"/");;){h=d.indexOf("/../");if(-1===h)break;else if(0===h){d=d.substring(3);break}g=d.substring(0,h).lastIndexOf("/");-1===g&&(g=h);d=d.substring(0,g)+d.substring(h+3)}c&&this.is("relative")&&(d=f?f+d:d.substring(1));d=b.recodePath(d);this._parts.path=d;this.build(!a);return this};e.normalizePathname=e.normalizePath;
e.normalizeQuery=function(a){"string"===typeof this._parts.query&&(this._parts.query.length?this.query(b.parseQuery(this._parts.query)):this._parts.query=null,this.build(!a));return this};e.normalizeFragment=function(a){this._parts.fragment||(this._parts.fragment=null,this.build(!a));return this};e.normalizeSearch=e.normalizeQuery;e.normalizeHash=e.normalizeFragment;e.iso8859=function(){var a=b.encode,c=b.decode;b.encode=escape;b.decode=decodeURIComponent;this.normalize();b.encode=a;b.decode=c;return this};
e.unicode=function(){var a=b.encode,c=b.decode;b.encode=k;b.decode=unescape;this.normalize();b.encode=a;b.decode=c;return this};e.readable=function(){var a=this.clone();a.username("").password("").normalize();var c="";a._parts.protocol&&(c+=a._parts.protocol+"://");a._parts.hostname&&(a.is("punycode")&&l?(c+=l.toUnicode(a._parts.hostname),a._parts.port&&(c+=":"+a._parts.port)):c+=a.host());a._parts.hostname&&(a._parts.path&&"/"!==a._parts.path[0])&&(c+="/");c+=a.path(!0);if(a._parts.query){for(var f=
"",h=0,g=a._parts.query.split("&"),e=g.length;h<e;h++){var m=(g[h]||"").split("="),f=f+("&"+b.decodeQuery(m[0]).replace(/&/g,"%26"));m[1]!==d&&(f+="="+b.decodeQuery(m[1]).replace(/&/g,"%26"))}c+="?"+f.substring(1)}return c+=a.hash()};e.absoluteTo=function(a){var c=this.clone(),d=["protocol","username","password","hostname","port"];if(this._parts.urn)throw Error("URNs do not have any generally defined hierachical components");if(this._parts.hostname)return c;a instanceof b||(a=new b(a));for(var h=
0,g;g=d[h];h++)c._parts[g]=a._parts[g];"/"!==c.path()[0]&&(a=a.directory(),c._parts.path=(a?a+"/":"")+c._parts.path,c.normalizePath());c.build();return c};e.relativeTo=function(a){var c=this.clone(),d=["protocol","username","password","hostname","port"],h;if(this._parts.urn)throw Error("URNs do not have any generally defined hierachical components");a instanceof b||(a=new b(a));if("/"!==this.path()[0]||"/"!==a.path()[0])throw Error("Cannot calculate common path from non-relative URLs");h=b.commonPath(c.path(),
a.path());for(var a=a.directory(),g=0,e;e=d[g];g++)c._parts[e]=null;if(!h||"/"===h)return c;if(a+"/"===h)c._parts.path="./"+c.filename();else{d="../";h=RegExp("^"+j(h));for(a=a.replace(h,"/").match(/\//g).length-1;a--;)d+="../";c._parts.path=c._parts.path.replace(h,d)}c.build();return c};e.equals=function(a){var c=this.clone(),d=new b(a),h={},g={},a={},e;c.normalize();d.normalize();if(c.toString()===d.toString())return!0;h=c.query();g=d.query();c.query("");d.query("");if(c.toString()!==d.toString()||
h.length!==g.length)return!1;h=b.parseQuery(h);g=b.parseQuery(g);for(e in h)if(Object.prototype.hasOwnProperty.call(h,e)){if(i(h[e])){if(!i(g[e])||h[e].length!==g[e].length)return!1;h[e].sort();g[e].sort();c=0;for(d=h[e].length;c<d;c++)if(h[e][c]!==g[e][c])return!1}else if(h[e]!==g[e])return!1;a[e]=!0}for(e in g)if(Object.prototype.hasOwnProperty.call(g,e)&&!a[e])return!1;return!0};"undefined"!==typeof module&&module.exports?module.exports=b:window.URI=b})();
(function(d){var j=Object.prototype.hasOwnProperty,i="undefined"!==typeof module&&module.exports?require("./URI"):window.URI,k=function(d){if(k._cache[d])return k._cache[d];if(!(this instanceof k))return new k(d);this.expression=d;k._cache[d]=this;return this},e=function(d){this.data=d;this.cache={}},l=k.prototype,q={"":{prefix:"",separator:",",named:!1,empty_name_separator:!1,encode:"encode"},"+":{prefix:"",separator:",",named:!1,empty_name_separator:!1,encode:"encodeReserved"},"#":{prefix:"#",separator:",",
named:!1,empty_name_separator:!1,encode:"encodeReserved"},".":{prefix:".",separator:".",named:!1,empty_name_separator:!1,encode:"encode"},"/":{prefix:"/",separator:"/",named:!1,empty_name_separator:!1,encode:"encode"},";":{prefix:";",separator:";",named:!0,empty_name_separator:!1,encode:"encode"},"?":{prefix:"?",separator:"&",named:!0,empty_name_separator:!0,encode:"encode"},"&":{prefix:"&",separator:"&",named:!0,empty_name_separator:!0,encode:"encode"}};k._cache={};k.EXPRESSION_PATTERN=/\{([^a-zA-Z0-9%_]?)([^\}]+)(\}|$)/g;
k.VARIABLE_PATTERN=/^([^*:]+)((\*)|:(\d+))?$/;k.VARIABLE_NAME_PATTERN=/[^a-zA-Z0-9%_]/;k.expand=function(d,b){var h=q[d.operator],e=h.named?"Named":"Unnamed",i=d.variables,j=[],s,o,l;for(l=0;o=i[l];l++)s=b.get(o.name),s.val.length?j.push(k["expand"+e](s,h,o.explode,o.explode&&h.separator||",",o.maxlength,o.name)):s.type&&j.push("");return j.length?h.prefix+j.join(h.separator):""};k.expandNamed=function(g,b,h,e,p,j){var k="",o=b.encode,b=b.empty_name_separator,l=!g[o].length,a=2===g.type?"":i[o](j),
c,f,n;f=0;for(n=g.val.length;f<n;f++)(p?(c=i[o](g.val[f][1].substring(0,p)),2===g.type&&(a=i[o](g.val[f][0].substring(0,p)))):l?(c=i[o](g.val[f][1]),2===g.type?(a=i[o](g.val[f][0]),g[o].push([a,c])):g[o].push([d,c])):(c=g[o][f][1],2===g.type&&(a=g[o][f][0])),k&&(k+=e),h)?k+=a+(b||c?"=":"")+c:(f||(k+=i[o](j)+(b||c?"=":"")),2===g.type&&(k+=a+","),k+=c);return k};k.expandUnnamed=function(g,b,h,e,k){var j="",l=b.encode,b=b.empty_name_separator,o=!g[l].length,q,a,c,f;c=0;for(f=g.val.length;c<f;c++)k?a=
i[l](g.val[c][1].substring(0,k)):o?(a=i[l](g.val[c][1]),g[l].push([2===g.type?i[l](g.val[c][0]):d,a])):a=g[l][c][1],j&&(j+=e),2===g.type&&(q=k?i[l](g.val[c][0].substring(0,k)):g[l][c][0],j+=q,j=h?j+(b||a?"=":""):j+","),j+=a;return j};l.expand=function(d){var b="";(!this.parts||!this.parts.length)&&this.parse();d instanceof e||(d=new e(d));for(var h=0,m=this.parts.length;h<m;h++)b+="string"===typeof this.parts[h]?this.parts[h]:k.expand(this.parts[h],d);return b};l.parse=function(){var d=this.expression,
b=k.EXPRESSION_PATTERN,h=k.VARIABLE_PATTERN,e=k.VARIABLE_NAME_PATTERN,i=[],j=0,l,o,t;for(b.lastIndex=0;;){o=b.exec(d);if(null===o){i.push(d.substring(j));break}else i.push(d.substring(j,o.index)),j=o.index+o[0].length;if(q[o[1]]){if(!o[3])throw Error('Unclosed Expression "'+o[0]+'"');}else throw Error('Unknown Operator "'+o[1]+'" in "'+o[0]+'"');l=o[2].split(",");for(var a=0,c=l.length;a<c;a++){t=l[a].match(h);if(null===t)throw Error('Invalid Variable "'+l[a]+'" in "'+o[0]+'"');if(t[1].match(e))throw Error('Invalid Variable Name "'+
t[1]+'" in "'+o[0]+'"');l[a]={name:t[1],explode:!!t[3],maxlength:t[4]&&parseInt(t[4],10)}}if(!l.length)throw Error('Expression Missing Variable(s) "'+o[0]+'"');i.push({expression:o[0],operator:o[1],variables:l})}i.length||i.push(d);this.parts=i;return this};e.prototype.get=function(g){var b=this.data,h={type:0,val:[],encode:[],encodeReserved:[]},e;if(this.cache[g]!==d)return this.cache[g];this.cache[g]=h;b="[object Function]"===String(Object.prototype.toString.call(b))?b(g):"[object Function]"===
String(Object.prototype.toString.call(b[g]))?b[g](g):b[g];if(b===d||null===b)return h;if("[object Array]"===String(Object.prototype.toString.call(b))){e=0;for(g=b.length;e<g;e++)b[e]!==d&&null!==b[e]&&h.val.push([d,String(b[e])]);h.val.length&&(h.type=3)}else if("[object Object]"===String(Object.prototype.toString.call(b))){for(e in b)j.call(b,e)&&(b[e]!==d&&null!==b[e])&&h.val.push([e,String(b[e])]);h.val.length&&(h.type=2)}else h.type=1,h.val.push([d,String(b)]);return h};i.expand=function(d,b){var h=
(new k(d)).expand(b);return new i(h)};"undefined"!==typeof module&&module.exports?module.exports=k:window.URITemplate=k})();
(function(d,j){function i(b){return b.replace(/([.*+?^=!:${}()|[\]\/\\])/g,"\\$1")}function k(b){var e;d.each(["href","src","action"],function(d,g){return g in b?(e=g,!1):!0});return"input"===b.nodeName.toLowerCase()&&"image"!==b.type?j:e}var e="undefined"!==typeof module&&module.exports?require("./URIjs"):window.URI,l=/^([a-zA-Z]+)\s*([\^\$*]?=|:)\s*(['"]?)(.+)\3|^\s*([a-zA-Z0-9]+)\s*$/,q={},g={"=":function(b,d){return b===d},"^=":function(b,d){return!!(b+"").match(RegExp("^"+i(d),"i"))},"$=":function(b,
d){return!!(b+"").match(RegExp(i(d)+"$","i"))},"*=":function(b,d,e){"directory"==e&&(b+="/");return!!(b+"").match(RegExp(i(d),"i"))},"equals:":function(b,d){return b.equals(d)},"is:":function(b,d){return b.is(d)}};d.each("authority directory domain filename fragment hash host hostname href password path pathname port protocol query scheme search subdomain suffix tld username".split(" "),function(b,e){q[e]=true;d.attrHooks["uri:"+e]={get:function(b){return d(b).uri()[e]()},set:function(b,h){d(b).uri()[e](h);
return h}}});d.fn.uri=function(b){var d=this.first(),g=d.get(0),i=k(g);if(!i)throw Error('Element "'+g.nodeName+'" does not have either property: href, src, action');if(b!==j){var l=d.data("uri");if(l)return l.href(b);b instanceof e||(b=e(b))}else{if(b=d.data("uri"))return b;b=e(d.attr(i))}b._dom_element=g;b._dom_attribute=i;b.normalize();d.data("uri",b);return b};e.prototype.build=function(b){if(this._dom_element)this._string=e.build(this._parts),this._deferred_build=!1,this._dom_element.setAttribute(this._dom_attribute,
this._string),this._dom_element[this._dom_attribute]=this._string;else if(!0===b)this._deferred_build=!0;else if(b===j||this._deferred_build)this._string=e.build(this._parts),this._deferred_build=!1;return this};d.expr.filters.uri=function(b,e,i){if(!k(b)||!i[3])return!1;e=i[3].match(l);if(!e||!e[5]&&":"!==e[2]&&!g[e[2]])return!1;i=d(b).uri();if(e[5])return i.is(e[5]);if(":"===e[2])return b=e[1].toLowerCase()+":",!g[b]?!1:g[b](i,e[4]);b=e[1].toLowerCase();return!q[b]?!1:g[e[2]](i[b](),e[4],b)};var b=
function(b,e){return d(b).uri().href(e).toString()};d.each(["src","href","action","uri"],function(e,g){d.attrHooks[g]={set:b}});d.attrHooks.uri.get=function(b){return d(b).uri()}})(jQuery);
(function(d,j){var i=d.prototype,k=i.fragment;i.fragment=function(e,i){return!0===e?d.parseQuery(this._parts.fragment.substring(1)):e!==j&&"string"!==typeof e?(this._parts.fragment="?"+d.buildQuery(e),this.build(!i),this):k.call(this,e,i)};i.addFragment=function(e,i,j){var g=d.parseQuery(this._parts.fragment.substring(1));d.addQuery(g,e,i);this._parts.fragment="?"+d.buildQuery(g);"string"!==typeof e&&(j=i);this.build(!j);return this};i.removeFragment=function(e,i,j){var g=d.parseQuery(this._parts.fragment.substring(1));
d.removeQuery(g,e,i);this._parts.fragment="?"+d.buildQuery(g);"string"!==typeof e&&(j=i);this.build(!j);return this};i.addHash=i.addFragment;i.removeHash=i.removeFragment})(window.URI);
